CC = mpicxx
CFLAGS := -Wall -g


all			:	servidor anillo

	
anillo		:       anillo.cpp
	$(CC) $(CFLAGS) anillo.cpp -o anillo
	
servidor		:       servidor.cpp
	$(CC) $(CFLAGS) servidor.cpp -o servidor


 
